layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0, rgba32f) readonly uniform highp image2D stateIn;
layout(binding = 1, rgba32f) writeonly uniform highp image2D stateOut;
layout(binding = 2, r32f) readonly uniform highp image2D terrain;

uniform float dx;
uniform float dt;
uniform float gravity;
uniform float dryEps;
uniform float friction_coef;

void main() {
    uvec3 globalID = gl_GlobalInvocationID;
    
}