layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding=0, rgba32f) readonly uniform image2D texin;
layout(binding=1, rgba32f) writeonly uniform image2D texout;

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(texin);
    
    if (gid.x >= size.x || gid.y >= size.y) return;
    vec4 v = imageLoad(texin, gid);
    
    imageStore(texout, gid, v);
}
