layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding=0, rg32f) readonly uniform image2D u_input;
layout(binding=1, rg32f) writeonly uniform image2D u_output;

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(u_input);
    
    if (gid.x >= size.x || gid.y >= size.y) return;
    vec4 v = imageLoad(u_input, gid);
    
    imageStore(u_output, gid, v);
}
